In [1]:
## importing necessary libraries
import numpy as np
import pandas as pd
from sklearn.metrics import confusion_matrix

In [2]:
## defining variables
seed_value = (11,12) #for reproducible results
array_size = 200

seed_value, array_size

((11, 12), 200)

In [3]:
## generating actuals and predictions

np.random.seed(seed_value[0])
actuals = np.random.randint(0,2,array_size)

np.random.seed(seed_value[1])
predictions = np.random.randint(0,2,array_size)

print(actuals[:6])
print(predictions[:6])
print(actuals.size, predictions.size)

[1 1 0 1 1 1]
[1 1 0 1 1 0]
200 200


In [6]:
# forming confusion matrix (actuals/predictions on horizontal/vertical axis respectively)
# Hint : use confusion matric function which we imported earlier
from sklearn.metrics import confusion_matrix
cf=confusion_matrix(actuals,predictions)
print(cf)

[[58 40]
 [48 54]]


In [7]:
## Extract True Positive, True Negative, False Positive, False Negative
## Note that all these values are corresponding to class 1

#true positive
tp = 58

#false positive
fp = 48

#true negative
tn = 54

#false negative
fn = 40

print(tp,fp,tn,fn)

58 48 54 40


In [9]:
def get_metrics_from_confusion_matrix(conf_matrix):
    TP = conf_matrix[1, 1]
    FP = conf_matrix[0, 1]
    FN = conf_matrix[1, 0]
    TN = conf_matrix[0, 0]
    return TP, FP, FN, TN

# Example confusion matrix as a NumPy array
conf_matrix = np.array([[58, 40], [48, 54]])

# Get TP, FP, FN, TN from the confusion matrix
TP, FP, FN, TN = get_metrics_from_confusion_matrix(conf_matrix)

print(TP, FP, TN, FN)


54 40 58 48


In [12]:
## Calculate Precision
from sklearn.metrics import precision_score
precision=precision_score(actuals,predictions)
precision


## Calculate Recall
from sklearn.metrics import recall_score
recall=recall_score(actuals,predictions)
recall


## Calculate f1 score
f1=2/((1/precision)+(1/recall))
f1

precision, recall, f1

(0.574468085106383, 0.5294117647058824, 0.5510204081632654)